"""Add conversation sessions

Revision ID: 60d60d53fb68
Revises: cf399fe20568
Create Date: 2025-03-17 20:31:48.370189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d60d53fb68'
down_revision: Union[str, None] = 'cf399fe20568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'conversation_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'session_id')
    # ### end Alembic commands ###
